from Bio.Seq import Seq

s = Seq(
    "GAGCTAGTGAGCTAGGAGCTAGAATGAGCTAGTGTATAAGAGCTAGTGAGCTAGTTATGAGCTAGGTGGGAGCTAGGAGCTAGCCCGAGCTAGCCATGGAGCTAGTGAGCTAGTCGAGCTAGACCAGTCTGGAGCTAGGAGCTAGGAGCTAGACTGGAGCTAGGACTAGAGCTAGGGAGCTAGGTTAGAGCTAGCGATGCGAGCTAGATTGAGCTAGATAACTTGCACGAGCTAGTAGAGCTAGGAGCTAGCGAGCTAGGGAGCTAGTCGTACCCTTGAGCTAGTGAGCTAGGTTAAACAGAGCTAGAGGAGCTAGTAAGCGAGCTAGGAGCTAGGAGCTAGTTTGAGCTAGGAGCTAGAGAGCTAGTCGAGCTAGGAGCTAGTGAGCTAGCTCGGAGCTAGTCGAGCTAGCTTGAGCTAGGAGCTAGGAGCTAGTAGTGCGCTAATGAGCTAGGACGAGCTAGCGATGAGCTAGTGCACGAGCTAGCAAGGCTAGAAGAGCTAGTCCAACGTCAGGAGCTAGTCGAGCTAGTGAGGAGCTAGAGGAGCTAGGTGAGCTAGGATGAGCTAGGCCAATCCAAGAGCTAGGAGCTAGAGAGCTAGCAATGAGCTAGGAGCTAGGGAGCTAGGAGCTAGGGAGCTAGTTAGAGCTAGCGAGCTAGCCCAGCGAGCTAGGGAGCTAGCGGAGCTAGGGAGCTAGGGAGCTAGGGCGAGCTAGTCGTGAGCTAGTGAGCTAGGAGCTAGAGAGCTAGCAGAGCTAGCGAGCTAGGAGCTAGTAAAAGAGCTAGGAGCTAGACGAGCTAGCAGGAGCTAGGAGCTAGGAGCTAGGGCGTGAGCTAGTTCGAACCAGGAGCTAGATGTGAGCTAG")
t = Seq("GAGCTAGGA")

locations = []
count = 0
loc = 0

while (count < len(s)):
    loc = s.find(t, start=count)
    if (loc > 0):
        count = loc + 1
        locations.append(
            loc + 1)  # adding plus 1 since the result needs to be in count from 1 format
    else:
        count = count + 1

print(' '.join(map(str, locations)))
