"""
Given: A DNA string s of length at most 1000 bp.

Return: Four integers (separated by spaces) representing the respective number
of times that the symbols 'A', 'C', 'G', and 'T' occur in s. Note:
You must provide your answer in the format shown in the sample output below.

"""
dna_string = "CAACGCGTAATACCCAGACAAACTCAATACGTACATCTGAGCCAATGCCAGACTCACTGAAGGATCAAGCCAGGCGTCAATCCTCCGTGAGCACGTACATTAATGTCAATAAACGGTATACATTGGGGGCTGCTGAGGTACTTAGCAAGCGAGGAAATTGAGGTACCTGTCATAGGGAGGCTAGACTTGGGGACTATCCGGGCCTCACCTGTTCCCCTCACCGCGTTTTCCCGAAGTGTCAACCCTGTGCATGGATGCTCCCCTAAGCCTTCAGCGACGGTTGGCTAGCAGATATAGTCCTGGTGTTTTTCTCTGAGAGATACGTTTTTCTGTGTATAGATACTCTCTCCACAACTCGCCGCAACGATCCTGCATAATCCAGATGATACCGGCAGCAGCCCTTTAGGTAACTCTGAGCGATGCGAATTCGGCTCCAATCGCTTCATGAGCTCACTCGTAGTGGCATACTCTTAAATCGCACCGGAAGTAAGGACCTGCTGTACCGCTGTGGGAGGGGTTGCTACGGATCAGAGCCGCCAGTCGTGTTCAAGGATAATAATCGAAGGAACCGCCATGCGCTGAGGACCGTGTAAAAAGCGAGCTTGACGGCTAAGCCTCGGGATACATTGTTCGACGCCCTGCAGTGTCCGACTTATTGCAATCATGTCTCGCAAATACCAGTCAGTGTTGCGCCCCTACGATAACTAATCGAATCAGGTCTATGTACTAAGGGATTGTCCTCATTGTATTTGCGGAGACCCATAGGCCGCGAGGGTCGGTTCTCGCTACACTACTTTGTGTTGGACATATACTTCCGACGGGTACCAAAAAACAATACCGTTAATGGGCAAAGATACCCCAAGAACATGACCAACTAGACCCTTAGTGGTTTTTCCCGGTAAAGGTAATGCAGGCGTGTAGCAATCTAACATTGCAT"


A = dna_string.count('A')
C = dna_string.count('C')
G = dna_string.count('G')
T = dna_string.count('T')

print(A," ",C," ",G," ",T)